### ISSUE TITLE
Can't understand how to initialize Shablbot

### ISSUE THREAD

**Issue by imluza** [Blackgard/shablbot#4]
Can't understand how to initialize Shablbot. Where i should to type this command? 
 C:\shablbot> py -m shablbot --init
Big thanks

**Comment by Blackgard** [comment]
Hello, in order to initialize the bot, you must first install it using the "pip install shablbot" command. After that, in an empty folder where you want to place the bot files, you need to run the command "py -m shablbot --init".

Eg:
- I'll go to the cmd console or any other.
- I will go to the folder along the path with the command "cd C:\Users\user\Desktop\shablbot\"
- I will execute in the folder "python -m pip install shablbot"
- After successfully installing the module, I will execute the command "py -m shablbot --init"
- Ready!
